### ISSUE TITLE
How to run the project?

### ISSUE THREAD

**Issue by zyufoye** [WellingtonLobato/PyFlexe#2]
why after I run "python server_flexe.py --ip 127.0.0.1:5000 --dataset MNIST" , I can not receive any response, and then I should do anyother to run this project? thanks!

**Comment by WellingtonLobato** [comment]
Hi @zyufoye! Thanks for trying using PyFlexe! Did you install Omnet++? Did you follow the FLEXE steps? The project is made up of two parts. Once the PyFlexe server is up, you can start the simulation with Flexe.
Take a look in this part [here](https://github.com/WellingtonLobato/flexe)
